name: Docker Build Image and Deploy to Azure Container Registry
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.TEST_AZURE_REGISTRY }}
        username: ${{ secrets.TEST_ACR_USERNAME }}
        password: ${{ secrets.TEST_ACR_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.TEST_AZURE_REGISTRY }}/${{ github.event.repository.name }}:setup
# tags: ${{ secrets.AZURE_REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}

